- hosts: localhost
  var:
  - region: "region"
  - ins_type: "instance type"
  - ami: "ami_id"
  - key: "your keyname"
  - sg: "security group id"
  - subnet: "subnet id"
  tasks:
  - name: "Installing Python package"
    package:
       name: "python3"

  - name: "Installing boto3 library"
    pip:
       name: "boto3"
  - name: "Launching Master Instance"
    ec2_instance:
       region: "{{ region }}"
       name: "master"
       instance_type: "{{ ins_type }}"
       wait: yes
       wait_timeout: 20
       key_name: "{{ key }}"
       image_id: "{{ ami }}"
       security_group: "{{ sg }}"
       state: present
       vpc_subnet_id: "{{ subnet }}"
    register: master

  - name: "Launching Slave1 Instance"
    ec2_instance:
       region: "{{ region }}"
       name: "slave1"
       wait: yes
       wait_timeout: 20
       instance_type: "{{ ins_type }}"
       key_name: "{{ key }}"
       image_id: "{{ ami }}"
       security_group: "{{ sg }}"
       tags:
          group: slave
       state: present
       vpc_subnet_id: "{{ subnet }}"
    register: slave1

  - name: "Launching Slave2 Instance"
    ec2_instance:
       region: "{{ region }}"
       name: "slave2"
       tags:
          group: slave
       instance_type: "{{ ins_type }}"
       wait: yes
       wait_timeout: 20
       key_name: "{{ key }}"
       image_id: "{{ ami }}"
       security_group: "{{ sg }}"
       state: present
       vpc_subnet_id: "{{ subnet }}"
    register: slave2

  - name: Updating inventory 
    blockinfile:
       path: /Ansible_WorkStation/AWS/k8s-multi-node-cluster/hosts
       marker: "# 1st {mark} ANSIBLE MANAGED BLOCK "
       block: |
               [{{ master.instances[0].tags.Name }}]
               {{ master.instances[0].public_ip_address }}
               [{{ slave1.instances[0].tags.group }}]
               {{ slave1.instances[0].public_ip_address }}
               {{ slave2.instances[0].public_ip_address }}

